# Site settings
title: 攸溟的个人博客
email: celerysoft@gmail.com
description: > #攸溟的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://celerysoft.github.io" # the base hostname & protocol for your site

# Paginate（分页）
#gems: [jekyll-paginate]
# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
#highlighter: pygments
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day.html


# 博客作者相关
author:
  name: 攸溟
  email: celerysoft@gmail.com
  link: http://celerysoft.github.io/
  weibo: http://weibo.com/celerysoft
  weibo_username: 攸溟
  github: https://github.com/celerysoft
  github_username: celerysoft
  twitter: https://twitter.com/celerysoft
  twitter_username: celerysoft


locals:                                     #自定义常量
  tags: 标签
  about: 关于
  active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址

# 头像
avatar: /assets/image/favicon.ico
# 网站CSS路径
css: /assets/css/
#css: http://7xpapo.com1.z0.glb.clouddn.com/css/
# 网站JS路径
js: /assets/js/
#js: http://7xpapo.com1.z0.glb.clouddn.com/js/
# 网站图片路径
image: /assets/image/
#js: http://7xpapo.com1.z0.glb.clouddn.com/image/
# 博文图片路径
postimage: http://www.7xpapo.com1.z0.glb.clouddn.com/
#postimage: /assets/postImages/

# disqus 设置
disqus:
  shortname: celerysoft
