# Site settings
title: 攸溟的个人博客
email: celerysoft@gmail.com
description: > #攸溟的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://celerysoft.github.io" # the base hostname & protocol for your site
twitter_username: celerysoft@gmail.com
github_username:  celerysoft

# Paginate
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 10                #分页时每页博文数量

# Build settings
markdown: kramdown
permalink: /:year-:month-:day.html   #博文的固定链接
author:                                     #自定义常亮
  name: 攸溟
  email: celerysoft@gmail.com
  link: http://celerysoft.github.io/
  weibo: http://weibo.com/celerysoft
  github: http://github.com/celerysoft

# avatar头像及Favicon
#avatar: https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
avatar: favicon.ico
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
#markdown: redcarpet                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: celerysoft
